path_info:
  test_gt_path: '/home/diskhkme/data/PNID/EWP/Drawing_Segment/Dataset_800_300_0.5_Text_Rotated/test.json' # 학습 도면 분할시 생성한 test.json 파일 경로
  test_dt_path: '/home/diskhkme/Libs/_PNID/mmdetection/work-dir/s05_800_300_text_rotate/swin_t_fpn/result/result.bbox.json' # prediction 결과로 mmdetection에서 생성된 json 파일 경로
  test_big_sym_dt_path:
  output_dir: "/home/diskhkme/Libs/_PNID/mmdetection/work-dir/s05_800_300_text_rotate/swin_t_fpn/result_soft/" # 출력 파일들이 저장될 폴더

  base_dir: '/home/diskhkme/data/PNID/EWP/'

  # 이하 dir 및 path들은 모두 base_dir + XXX 로 정의됨
  drawing_img_dir: 'Drawing'
  symbol_xml_dir: 'SymbolXML'
  text_xml_dir: 'TextXML'
  symbol_dict_path: 'EWP_SymbolClass_sym_only.txt'
  symbol_type_dict_path:

# 이하 options들은 학습 데이터와 동일해야 함
options:
  include_text_as_class: True
  include_text_orientation_as_class: True

  drawing_resize_scale: 0.5
  segment_width: 800
  segment_height: 800
  segment_stride_w: 300
  segment_stride_h: 300

metric_param:
  score_threshold: 0.5  # score filtering threshold
  matching_iou_threshold: 0.5  # 매칭(정답) 처리할 IOU threshold
  nms_method: 'soft' # greedy/soft
  nms_threshold: 0.0
  adaptive_thr_dict:
    311: 0.02
    66: 0.06
    145: 0.4
    131: 0.65
    431: 0.04
    109: 0.03
    239: 0.3
    12: 0.0002